my_string = input("Введите длину: ")
print("Длина веревки,", my_string)
print('my string' .upper())
print('my string' .lower())
print('my string' .replace(' ', ''))
print('my string'[0])
print('my string'[-1])
